### ISSUE TITLE
运行包版本问题

### ISSUE THREAD

**Issue by skylorh** [zzh816/WKAFL-code#1]
你好，我在运行WKAFL-code项目中的EMNIST-ByClass/EMNIST_GSGM.py的时候报了如下错误：
```
Traceback (most recent call last):
  File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\tensors\interpreters\native.py", line 336, in handle_func_command
    new_args, new_kwargs, new_type, args_type = hook_args.unwrap_args_from_function(
  File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook_args.py", line 167, in unwrap_args_from_function
    new_args = args_hook_function(args_)
  File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook_args.py", line 356, in <lambda>
    return lambda x: f(lambdas, x)
  File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook_args.py", line 523, in tuple_one_fold
    return (lambdas[0](args_[0], **kwargs),)
  File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook_args.py", line 331, in <lambda>
    else lambda i: forward_func[type(i)](i)
  File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\hook\hook_args.py", line 24, in <lambda>
    else (_ for _ in ()).throw(PureFrameworkTensorFoundError),
  File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\hook\hook_args.py", line 24, in <genexpr>
    else (_ for _ in ()).throw(PureFrameworkTensorFoundError),
syft.exceptions.PureFrameworkTensorFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/await/github/WKAFL-code/EMNIST-ByClass/EMNIST_GSGM.py", line 143, in <module>
    federated_data, datasNum, selectWriter = DatasetsLoader.dataset_federate_noniid(datasets, workers, args)
  File "C:\Users\await\github\WKAFL-code\EMNIST-ByClass\DatasetsLoader.py", line 157, in dataset_federate_noniid
    for i in range(torch.max(writers)):
  File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook.py", line 335, in overloaded_func
    response = handle_func_command(command)
  File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\tensors\interpreters\native.py", line 380, in handle_func_command
    response = cls._get_response(cmd, args_, kwargs_)
  File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\tensors\interpreters\native.py", line 414, in _get_response
    response = command_method(*args_, **kwargs_)
RuntimeError: invalid argument 1: cannot perform reduction function max on tensor with no elements because the operation does not have an identity at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensorEvenMoreMath.cpp:370

```
我的环境是
```
python      3.8
syft            0.2.9
syft-proto  0.5.3
torch          1.4.0
torchvision 0.5.0
```
可能是我用的包版本不太兼容，可以把项目运行的必要包版本在readme里面告知一下吗

**Comment by z555a** [comment]
> 你好，我在运行 WKAFL-code 项目中的 EMNIST-ByClass/EMNIST_GSGM.py 的时候报了以下错误：
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\tensors\interpreters\native.py", line 336, in handle_func_command
>     new_args, new_kwargs, new_type, args_type = hook_args.unwrap_args_from_function(
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook_args.py", line 167, in unwrap_args_from_function
>     new_args = args_hook_function(args_)
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook_args.py", line 356, in <lambda>
>     return lambda x: f(lambdas, x)
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook_args.py", line 523, in tuple_one_fold
>     return (lambdas[0](args_[0], **kwargs),)
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook_args.py", line 331, in <lambda>
>     else lambda i: forward_func[type(i)](i)
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\hook\hook_args.py", line 24, in <lambda>
>     else (_ for _ in ()).throw(PureFrameworkTensorFoundError),
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\hook\hook_args.py", line 24, in <genexpr>
>     else (_ for _ in ()).throw(PureFrameworkTensorFoundError),
> syft.exceptions.PureFrameworkTensorFoundError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:/Users/await/github/WKAFL-code/EMNIST-ByClass/EMNIST_GSGM.py", line 143, in <module>
>     federated_data, datasNum, selectWriter = DatasetsLoader.dataset_federate_noniid(datasets, workers, args)
>   File "C:\Users\await\github\WKAFL-code\EMNIST-ByClass\DatasetsLoader.py", line 157, in dataset_federate_noniid
>     for i in range(torch.max(writers)):
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook.py", line 335, in overloaded_func
>     response = handle_func_command(command)
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\tensors\interpreters\native.py", line 380, in handle_func_command
>     response = cls._get_response(cmd, args_, kwargs_)
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\tensors\interpreters\native.py", line 414, in _get_response
>     response = command_method(*args_, **kwargs_)
> RuntimeError: invalid argument 1: cannot perform reduction function max on tensor with no elements because the operation does not have an identity at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensorEvenMoreMath.cpp:370
> ```
> 
> 我的发展是
> 
> ```
> python      3.8
> syft            0.2.9
> syft-proto  0.5.3
> torch          1.4.0
> torchvision 0.5.0
> ```
> 
> 可能是我用的包版本不太兼容，可以把项目运行的必要包版本在readme里面告知一下吗

你好！你后面这个项目跑成功了吗， 我也在复现这个，能不能提供一下软件安装包呢

**Comment by zzh816** [comment]
你好，这个是几年前写的代码，当时torch使用的是0.4.0版本，python使用的3.5.0,syft好像是0.2.9，具体记不清楚了


-----原始邮件-----
发件人:z555a ***@***.***>
发送时间:2025-01-17 13:52:53 (星期五)
收件人: zzh816/WKAFL-code ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [zzh816/WKAFL-code] 运行包版本问题 (Issue #1)






你好，我在运行 WKAFL-code 项目中的 EMNIST-ByClass/EMNIST_GSGM.py 的时候报了以下错误：

Traceback (most recent call last):
  File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\tensors\interpreters\native.py", line 336, in handle_func_command
    new_args, new_kwargs, new_type, args_type = hook_args.unwrap_args_from_function(
  File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook_args.py", line 167, in unwrap_args_from_function
    new_args = args_hook_function(args_)
  File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook_args.py", line 356, in <lambda>
    return lambda x: f(lambdas, x)
  File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook_args.py", line 523, in tuple_one_fold
    return (lambdas[0](args_[0], **kwargs),)
  File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook_args.py", line 331, in <lambda>
    else lambda i: forward_func[type(i)](i)
  File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\hook\hook_args.py", line 24, in <lambda>
    else (_ for _ in ()).throw(PureFrameworkTensorFoundError),
  File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\hook\hook_args.py", line 24, in <genexpr>
    else (_ for _ in ()).throw(PureFrameworkTensorFoundError),
syft.exceptions.PureFrameworkTensorFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/await/github/WKAFL-code/EMNIST-ByClass/EMNIST_GSGM.py", line 143, in <module>
    federated_data, datasNum, selectWriter = DatasetsLoader.dataset_federate_noniid(datasets, workers, args)
  File "C:\Users\await\github\WKAFL-code\EMNIST-ByClass\DatasetsLoader.py", line 157, in dataset_federate_noniid
    for i in range(torch.max(writers)):
  File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook.py", line 335, in overloaded_func
    response = handle_func_command(command)
  File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\tensors\interpreters\native.py", line 380, in handle_func_command
    response = cls._get_response(cmd, args_, kwargs_)
  File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\tensors\interpreters\native.py", line 414, in _get_response
    response = command_method(*args_, **kwargs_)
RuntimeError: invalid argument 1: cannot perform reduction function max on tensor with no elements because the operation does not have an identity at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensorEvenMoreMath.cpp:370 

我的发展是

python      3.8
syft            0.2.9
syft-proto  0.5.3
torch          1.4.0
torchvision 0.5.0 

可能是我用的包版本不太兼容，可以把项目运行的必要包版本在readme里面告知一下吗

你好！你后面这个项目跑成功了吗， 我也在复现这个，能不能提供一下软件安装包呢

**Comment by z555a** [comment]
> 你好，这个是几年前写的代码，当时torch使用的是0.4.0版本，python使用的3.5.0,syft好像是0.2.9，具体记不清楚了
> […](#)
> 
> -----原始邮件-----
> 发件人:z555a ***@***.***>
> 发送时间:2025-01-17 13:52:53 (星期五)
> 收件人: zzh816/WKAFL-code ***@***.***>
> 抄送: Subscribed ***@***.***>
> 主题: Re: [zzh816/WKAFL-code] 运行包版本问题 (Issue [#1](https://github.com/zzh816/WKAFL-code/issues/1))
> 
> 
> 
> 
> 
> 
> 你好，我在运行 WKAFL-code 项目中的 EMNIST-ByClass/EMNIST_GSGM.py 的时候报了以下错误：
> 
> Traceback (most recent call last):
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\tensors\interpreters\native.py", line 336, in handle_func_command
>     new_args, new_kwargs, new_type, args_type = hook_args.unwrap_args_from_function(
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook_args.py", line 167, in unwrap_args_from_function
>     new_args = args_hook_function(args_)
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook_args.py", line 356, in <lambda>
>     return lambda x: f(lambdas, x)
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook_args.py", line 523, in tuple_one_fold
>     return (lambdas[0](args_[0], **kwargs),)
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook_args.py", line 331, in <lambda>
>     else lambda i: forward_func[type(i)](i)
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\hook\hook_args.py", line 24, in <lambda>
>     else (_ for _ in ()).throw(PureFrameworkTensorFoundError),
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\hook\hook_args.py", line 24, in <genexpr>
>     else (_ for _ in ()).throw(PureFrameworkTensorFoundError),
> syft.exceptions.PureFrameworkTensorFoundError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:/Users/await/github/WKAFL-code/EMNIST-ByClass/EMNIST_GSGM.py", line 143, in <module>
>     federated_data, datasNum, selectWriter = DatasetsLoader.dataset_federate_noniid(datasets, workers, args)
>   File "C:\Users\await\github\WKAFL-code\EMNIST-ByClass\DatasetsLoader.py", line 157, in dataset_federate_noniid
>     for i in range(torch.max(writers)):
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\generic\frameworks\hook\hook.py", line 335, in overloaded_func
>     response = handle_func_command(command)
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\tensors\interpreters\native.py", line 380, in handle_func_command
>     response = cls._get_response(cmd, args_, kwargs_)
>   File "C:\Users\await\anaconda3\lib\site-packages\syft\frameworks\torch\tensors\interpreters\native.py", line 414, in _get_response
>     response = command_method(*args_, **kwargs_)
> RuntimeError: invalid argument 1: cannot perform reduction function max on tensor with no elements because the operation does not have an identity at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensorEvenMoreMath.cpp:370
> 
> 我的发展是
> 
> python      3.8
> syft            0.2.9
> syft-proto  0.5.3
> torch          1.4.0
> torchvision 0.5.0
> 
> 可能是我用的包版本不太兼容，可以把项目运行的必要包版本在readme里面告知一下吗
> 
> 你好！你后面这个项目跑成功了吗， 我也在复现这个，能不能提供一下软件安装包呢
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

好的谢谢！版本包兼容，我复现起来比较困难，有些错挺奇怪的。我现在还是新手哈哈哈
